apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      # manage pods with the label app: nginx
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: some-redis
        image: redis
        ports:
        - containerPort: 1880
          hostPort: 8000